framework:
    default_locale: en
    translator:
        paths:
            - '%kernel.project_dir%/translations/auth/dist'
            - '%kernel.project_dir%/translations/auth/src'
        fallbacks:
            - en
